"""Canonical Pydantic schemas for AgentForge.

All implementation skills import from this package and never invent types.
New types are added via ADR through ``agentforge-architect``.
"""

from __future__ import annotations

from agentforge.schemas.artifact import (
    Artifact,
    ArtifactType,
    ExecutionObservation,
    PerTestResult,
    TestResults,
    UploadedFile,
)
from agentforge.schemas.common import (
    ActorType,
    ApprovalStatus,
    AuthorPhase,
    ErrorCode,
    RepairPhase,
    RiskLevel,
    SessionStatus,
    Severity,
    StrictModel,
    TerminalSessionStatus,
    ToolPhase,
    Workflow,
)
from agentforge.schemas.eval import (
    AdversarialScenario,
    AdversarialSubkind,
    AuthorScenario,
    EvalKind,
    EvalRunResult,
    EvalRunSummary,
    EvalScenario,
    ExpectedAfterFix,
    ExpectedDiagnosis,
    ExpectedPatch,
    GoldenOutputSpec,
    RepairScenario,
)
from agentforge.schemas.event import EventKind, WorkspaceEvent
from agentforge.schemas.responses import (
    ApprovalActionResponse,
    ApprovalDeclineRequest,
    ApprovalGrantRequest,
    AuditExportResponse,
    ChainCheck,
    FileUploadResponse,
    LoadFixtureResponse,
    SessionAnswerRequest,
    SessionAnswerResponse,
    SessionArchiveResponse,
    SessionCancelResponse,
    SessionEventsResponse,
    SessionRestoreResponse,
    SessionFinaliseRequest,
    SessionFinaliseResponse,
    SessionRunRequest,
    SessionRunResponse,
    UploadAgentZipResponse,
)
from agentforge.schemas.session import (
    ArtifactSummary,
    BudgetStatus,
    CompletionFailureMetadata,
    CompletionMetadata,
    FailureMitigation,
    MitigationAction,
    ResumeManifest,
    Session,
    SessionBudgetBreakdownItem,
    SessionBudgetSummary,
    SessionCreate,
    SessionList,
    SessionListItem,
    SessionListView,
    ValidationLayerSummary,
)
from agentforge.schemas.tool import (
    ApprovalDecision,
    ApprovalRequest,
    ToolDefinition,
    ToolInvocation,
    ToolObservation,
)
from agentforge.schemas.validation import (
    FilesChangedEntry,
    RepairReport,
    TestRunSummary,
    ValidationCheck,
    ValidationLayer,
    ValidationReport,
)
from agentforge.schemas.workflow import (
    AgentSummary,
    AuthorRequirements,
    BusinessRule,
    ColumnProfile,
    Diagnosis,
    FileProfile,
    PatchProposal,
    PendingQuestion,
    ProblemClassification,
    QuestionAnswer,
    QuestionStyle,
    RepairProblem,
    ReproductionMethod,
    ReproductionResult,
)

__all__ = [
    # common
    "ActorType",
    "ApprovalStatus",
    "AuthorPhase",
    "ErrorCode",
    "RepairPhase",
    "RiskLevel",
    "SessionStatus",
    "Severity",
    "StrictModel",
    "TerminalSessionStatus",
    "ToolPhase",
    "Workflow",
    # session
    "ArtifactSummary",
    "BudgetStatus",
    "CompletionFailureMetadata",
    "CompletionMetadata",
    "FailureMitigation",
    "MitigationAction",
    "ResumeManifest",
    "Session",
    "SessionBudgetBreakdownItem",
    "SessionBudgetSummary",
    "SessionCreate",
    "SessionList",
    "SessionListItem",
    "SessionListView",
    "ValidationLayerSummary",
    # event
    "EventKind",
    "WorkspaceEvent",
    # responses
    "ApprovalActionResponse",
    "ApprovalDeclineRequest",
    "ApprovalGrantRequest",
    "AuditExportResponse",
    "ChainCheck",
    "FileUploadResponse",
    "LoadFixtureResponse",
    "SessionAnswerRequest",
    "SessionAnswerResponse",
    "SessionArchiveResponse",
    "SessionEventsResponse",
    "SessionRestoreResponse",
    "SessionCancelResponse",
    "SessionFinaliseRequest",
    "SessionFinaliseResponse",
    "SessionRunRequest",
    "SessionRunResponse",
    "UploadAgentZipResponse",
    # tool
    "ApprovalDecision",
    "ApprovalRequest",
    "ToolDefinition",
    "ToolInvocation",
    "ToolObservation",
    # workflow
    "AgentSummary",
    "AuthorRequirements",
    "BusinessRule",
    "ColumnProfile",
    "Diagnosis",
    "FileProfile",
    "PatchProposal",
    "PendingQuestion",
    "ProblemClassification",
    "QuestionAnswer",
    "QuestionStyle",
    "ReproductionMethod",
    "ReproductionResult",
    "RepairProblem",
    # validation
    "FilesChangedEntry",
    "RepairReport",
    "TestRunSummary",
    "ValidationCheck",
    "ValidationLayer",
    "ValidationReport",
    # artifact
    "Artifact",
    "ArtifactType",
    "ExecutionObservation",
    "PerTestResult",
    "TestResults",
    "UploadedFile",
    # eval
    "AdversarialScenario",
    "AdversarialSubkind",
    "AuthorScenario",
    "EvalKind",
    "EvalRunResult",
    "EvalRunSummary",
    "EvalScenario",
    "ExpectedAfterFix",
    "ExpectedDiagnosis",
    "ExpectedPatch",
    "GoldenOutputSpec",
    "RepairScenario",
]
