/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit/export/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Audit
         * @description Return the full event log + manifest for a session, JSON-serialised.
         *
         *     The response is self-contained: a downstream auditor can reconstruct
         *     "what happened" from this payload alone (subject to the prototype's
         *     append-only-by-convention contract; production hardens this with a
         *     storage-level CHECK + integrity-hash chain — see ADR-0004).
         */
        get: operations["export_audit_audit_export__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Eval Run
         * @description Return the most recent EvalRunSummary, or 404 if none recorded.
         */
        get: operations["get_latest_eval_run_evals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Eval Run
         * @description Run every bundled scenario synchronously; persist + return the summary.
         *
         *     The runner takes <10s for the three current scenarios on a warm
         *     machine, so we run inline rather than via the BP8 background
         *     supervisor. If the suite grows past comfortable response times,
         *     flip this to background + polling.
         */
        post: operations["trigger_eval_run_evals_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — always returns 200 if the process is alive.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — checks DB connectivity and the configured LLM backend.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Placeholder for the production observability extension.
         *
         *     Phase 1 does not implement Prometheus exposition; documented in
         *     DEPLOYMENT.md as a production extension.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List sessions, newest-first.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new author or repair session.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/budget/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Budget Summary
         * @description Return lifetime token usage aggregated across all sessions.
         */
        get: operations["get_budget_summary_sessions_budget_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Fetch session detail (status, phase, budgets, current step).
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session Endpoint
         * @description Remove a session from the dashboard (soft) or erase it permanently.
         */
        delete: operations["delete_session_endpoint_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Answer
         * @description Record an ``answer_received`` event for a paused session.
         *
         *     The agent loop currently emits ``question_asked`` via the
         *     ``ask_user`` tool (BP5a). This endpoint persists the reply; the
         *     next ``POST /sessions/{id}/run`` call resumes the loop with the
         *     answer visible in the event log.
         */
        post: operations["submit_answer_sessions__session_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Grant approval for a pending request.
         *
         *     The ``request_id`` in the body must correspond to an
         *     ``APPROVAL_REQUESTED`` event in the session's log. The matching
         *     request's ``step`` is copied onto the granted event so the agent
         *     loop's per-step approval gate (INV-3) sees the decision on resume.
         */
        post: operations["approve_sessions__session_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Session Endpoint
         * @description Archive a session so it no longer appears on the dashboard.
         */
        post: operations["archive_session_endpoint_sessions__session_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/archive.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Archive
         * @description Stream the full session archive ZIP.
         *
         *     If ``archive.zip`` does not exist yet (the agent never called
         *     ``archive_workspace``), build it now and emit an
         *     ``ARTIFACT_GENERATED`` event. Subsequent calls return the cached
         *     file. Sessions with no load-bearing contents (no reports / outputs
         *     / generated / working) yield 409 — the wizard surfaces this as
         *     "nothing to archive yet."
         */
        get: operations["download_archive_sessions__session_id__archive_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/artifacts/{relative_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Artifact
         * @description Stream an individual artifact from the session workspace.
         *
         *     Allowed prefixes: ``reports/``, ``outputs/``, ``generated/``,
         *     ``working/``. Everything else is rejected at the boundary
         *     (uploads/ excluded — they're the user's own files; events.jsonl
         *     + manifest.json served via /audit/export and the archive).
         *
         *     INV-5: the path is resolved through ``WorkspaceManager.resolve_in``
         *     so ``..`` and absolute paths are rejected. Content-Type is
         *     inferred from the extension (``text/markdown`` for ``.md``,
         *     ``text/csv`` for ``.csv``, etc.).
         */
        get: operations["download_artifact_sessions__session_id__artifacts__relative_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Session Endpoint
         * @description Cancel a running or paused workflow.
         *
         *     Stops any active background task, records ``USER_ABANDONED``, and
         *     marks the session ``failed_other``. Terminal sessions return 409.
         */
        post: operations["cancel_session_endpoint_sessions__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Session Events
         * @description Return events for a session in chronological order.
         *
         *     The frontend polls this every 2 seconds while a session is RUNNING.
         */
        get: operations["list_session_events_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a CSV or XLSX into the session workspace.
         *
         *     Validates filename extension and MIME type BEFORE reading the body;
         *     enforces single-file and per-session total size limits; rejects
         *     uploads if the session has reached its file-count budget.
         */
        post: operations["upload_file_sessions__session_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise Session Endpoint
         * @description Mark the session COMPLETED in both manifest and DB row.
         *
         *     Refuses without an ``ARTIFACT_GENERATED`` event, mirroring the
         *     tool-side ``finalise_session`` guard so the HTTP path can never
         *     "complete" a session that produced no artifact (defends the
         *     promise in WORKFLOWS.md §1 step 12).
         */
        post: operations["finalise_session_endpoint_sessions__session_id__finalise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/load_fixture/{fixture_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Fixture
         * @description Copy a bundled broken-agent fixture into the session's workspace.
         *
         *     Emits one ``decision_input`` event recording the fixture choice
         *     plus one ``file_uploaded`` event per copied file so the audit log
         *     + wizard upload list reflect the load.
         */
        post: operations["load_fixture_sessions__session_id__load_fixture__fixture_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Decline a pending approval. ``reason`` is required (ADR-0006).
         *
         *     A decline transitions the loop to bounded decline-cycle behaviour
         *     (per ADR-0006, max 2 iterations before terminal ``failed_user_reject``).
         *     BP5b records the event; BP5c's orchestrator implements the cycle
         *     accounting.
         */
        post: operations["reject_sessions__session_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Session Endpoint
         * @description Restore an archived or recently deleted session to the active list.
         */
        post: operations["restore_session_endpoint_sessions__session_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Session
         * @description Dispatch the workflow flow on a background task.
         *
         *     Idempotency gate (INV-7):
         *       * Unknown session → 404.
         *       * Status RUNNING with an active background task → 409.
         *       * Status RUNNING without an active task → recover as interrupted,
         *         then allow a fresh run.
         *       * Status COMPLETED → 409 (no re-spawn).
         *
         *     Any other status (CREATED, PAUSED_*, FAILED_*) is permitted to
         *     (re)start a run. For the failed family the loop builds its own
         *     initial messages from the event log so prior progress shows up in
         *     the model's context.
         */
        post: operations["run_session_sessions__session_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/upload_agent_zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Agent Zip
         * @description Extract a user-supplied broken-agent ZIP into ``working/``.
         *
         *     Complementary to :func:`load_fixture` — the picker handles
         *     bundled demos, this endpoint handles real customer ZIPs. Same
         *     downstream semantics (populates ``working/`` + stages
         *     ``evals/expected_output.csv`` if the ZIP carries one), same
         *     INV-5 path discipline.
         *
         *     Defences:
         *       * **Zip-slip:** every entry's path is resolved through
         *         :meth:`WorkspaceManager.resolve_in`; any entry that would
         *         write outside ``working/`` triggers a rollback + 400.
         *       * **Zip-bomb:** per-entry cap (10 MiB uncompressed) + aggregate
         *         cap (100 MiB) + max-file-count cap (100). The aggregate is
         *         tracked as we extract — we stop + roll back when the limit
         *         is hit rather than after.
         *       * **MIME / name:** content type must be ``application/zip`` /
         *         ``application/x-zip-compressed`` / ``application/octet-stream``
         *         (browsers vary). Filename extension must be ``.zip``.
         *
         *     On any failure the partially-extracted ``working/`` is cleared so
         *     the session remains in a clean state for a retry.
         */
        post: operations["upload_agent_zip_sessions__session_id__upload_agent_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorType
         * @enum {string}
         */
        ActorType: "user" | "system" | "model";
        /**
         * ApprovalActionResponse
         * @description Common response for /approve and /reject.
         */
        ApprovalActionResponse: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["ApprovalStatus"];
        };
        /**
         * ApprovalDeclineRequest
         * @description POST /sessions/{id}/reject body.
         *
         *     Per ADR-0006, decline requires a ``reason``; the UI surfaces this
         *     in the ApprovalPanel's free-text field. Empty strings are rejected
         *     at the boundary.
         */
        ApprovalDeclineRequest: {
            /**
             * Decided By
             * @default user-demo
             */
            decided_by: string;
            /** Reason */
            reason: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /**
         * ApprovalGrantRequest
         * @description POST /sessions/{id}/approve body.
         *
         *     The ``request_id`` matches the ``request_id`` field in the
         *     ``APPROVAL_REQUESTED`` event payload emitted by the agent loop
         *     when it paused. ``decided_by`` records the actor; for the single-
         *     user demo it defaults to the demo user id.
         */
        ApprovalGrantRequest: {
            /**
             * Decided By
             * @default user-demo
             */
            decided_by: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "granted" | "declined";
        /**
         * ArtifactSummary
         * @description Per-artifact entry rolled into the manifest at finalisation.
         */
        ArtifactSummary: {
            /** Artifact Type */
            artifact_type: string;
            /** Hash Sha256 */
            hash_sha256?: string | null;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /**
         * AuditExportResponse
         * @description GET /audit/export/{session_id} response.
         *
         *     The full append-only event log plus the manifest, so a downstream
         *     auditor can reconstruct the session without consulting other sources.
         */
        AuditExportResponse: {
            chain_check: components["schemas"]["ChainCheck"];
            /** Event Count */
            event_count: number;
            /** Events */
            events: components["schemas"]["WorkspaceEvent"][];
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
            manifest: components["schemas"]["ResumeManifest"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** Body_upload_agent_zip_sessions__session_id__upload_agent_zip_post */
        Body_upload_agent_zip_sessions__session_id__upload_agent_zip_post: {
            /** File */
            file: string;
        };
        /** Body_upload_file_sessions__session_id__files_post */
        Body_upload_file_sessions__session_id__files_post: {
            /** File */
            file: string;
        };
        /**
         * BudgetStatus
         * @description Per-session budget counters and limits.
         */
        BudgetStatus: {
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /**
             * File Count Limit
             * @default 20
             */
            file_count_limit: number;
            /**
             * Steps Limit
             * @default 25
             */
            steps_limit: number;
            /**
             * Steps Used
             * @default 0
             */
            steps_used: number;
            /**
             * Tokens Limit
             * @default 150000
             */
            tokens_limit: number;
            /**
             * Tokens Used
             * @default 0
             */
            tokens_used: number;
            /**
             * Tool Calls Limit
             * @default 40
             */
            tool_calls_limit: number;
            /**
             * Tool Calls Used
             * @default 0
             */
            tool_calls_used: number;
            /**
             * Wall Seconds Limit
             * @default 1500
             */
            wall_seconds_limit: number;
            /**
             * Wall Seconds Used
             * @default 0
             */
            wall_seconds_used: number;
        };
        /**
         * ChainCheck
         * @description Light chain-integrity check (production extension upgrades this to a signed hash chain).
         */
        ChainCheck: {
            /** Message */
            message?: string | null;
            /** Valid */
            valid: boolean;
        };
        /**
         * CompletionFailureMetadata
         * @description Diagnostic metadata for stopped custom workflow builds.
         */
        CompletionFailureMetadata: {
            /** Error Code */
            error_code?: string | null;
            /** Failed Check */
            failed_check?: string | null;
            /** Failed Layer */
            failed_layer?: string | null;
            /** Pytest Failed */
            pytest_failed?: number | null;
            /** Pytest Passed */
            pytest_passed?: number | null;
            /** Pytest Summary */
            pytest_summary?: string | null;
            /** Validation Failures */
            validation_failures?: string[];
        };
        /**
         * CompletionMetadata
         * @description Provenance + reproducibility metadata persisted on the manifest.
         *
         *     Written once at terminal status; downstream consumers (the
         *     SESSION_README, the audit endpoints, the wizard's provenance card)
         *     read from here rather than re-aggregating the event stream.
         */
        CompletionMetadata: {
            /** After Fix Log Path */
            after_fix_log_path?: string | null;
            /** After Fix Pytest Summary */
            after_fix_pytest_summary?: string | null;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactSummary"][];
            /** Authoring Provenance Artifacts */
            authoring_provenance_artifacts?: string[];
            /** Before Fix Log Path */
            before_fix_log_path?: string | null;
            /** Before Fix Pytest Summary */
            before_fix_pytest_summary?: string | null;
            /** Build Mode */
            build_mode?: string | null;
            /** Changed Files */
            changed_files?: string[];
            /** Completion Via */
            completion_via?: string | null;
            failure?: components["schemas"]["CompletionFailureMetadata"] | null;
            /** Input File */
            input_file?: string | null;
            /** Input Format */
            input_format?: string | null;
            /** Llm Base Url */
            llm_base_url?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Provider */
            llm_provider?: string | null;
            /**
             * Model Call Count
             * @default 0
             */
            model_call_count: number;
            /**
             * Model Contributed
             * @default false
             */
            model_contributed: boolean;
            /** Model Contributed Files */
            model_contributed_files?: string[];
            /** Model Stages */
            model_stages?: string[];
            /** Normalized Input Path */
            normalized_input_path?: string | null;
            /** Output Hash */
            output_hash?: string | null;
            /** Output Path */
            output_path?: string | null;
            /** Patch Applied */
            patch_applied?: boolean | null;
            /** Patch Diff Path */
            patch_diff_path?: string | null;
            /** Post Fix Tests Passed */
            post_fix_tests_passed?: boolean | null;
            /**
             * Recovery Used
             * @default false
             */
            recovery_used: boolean;
            /** Repair Report Json Path */
            repair_report_json_path?: string | null;
            /** Repair Report Path */
            repair_report_path?: string | null;
            /** Repair Reproduced */
            repair_reproduced?: boolean | null;
            /** Selected Sheet */
            selected_sheet?: string | null;
            /** Skipped Layers */
            skipped_layers?: string[];
            /** Template Name */
            template_name?: string | null;
            /**
             * Tests Passed
             * @default false
             */
            tests_passed: boolean;
            /** Tests Path */
            tests_path?: string | null;
            /**
             * Tokens Used
             * @default 0
             */
            tokens_used: number;
            /** Validation Overall */
            validation_overall?: string | null;
            /**
             * Validation Passed
             * @default false
             */
            validation_passed: boolean;
            /** Validation Report Hash */
            validation_report_hash?: string | null;
            /** Validation Report Path */
            validation_report_path?: string | null;
            /** Validation Summary */
            validation_summary?: components["schemas"]["ValidationLayerSummary"][];
            /** Warnings */
            warnings?: string[];
            /** Workflow Report Hash */
            workflow_report_hash?: string | null;
            /** Workflow Report Path */
            workflow_report_path?: string | null;
            /** Workflow Type */
            workflow_type?: string | null;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "malformed_csv" | "unsupported_file_type" | "file_too_large" | "upload_limit_exceeded" | "missing_required_columns" | "ambiguous_schema" | "tool_not_registered" | "validation_loop_exhausted" | "generated_code_failed" | "test_failed" | "command_timeout" | "repair_cannot_reproduce" | "author_intent_schema_mismatch" | "author_custom_workflow_not_validated" | "author_custom_build_failed" | "author_validation_failed" | "universal_validation_failed" | "contract_specific_validation_failed" | "generated_pytest_failed" | "golden_output_comparison_failed" | "safety_validation_failed" | "artifact_validation_failed" | "author_model_required_for_custom_build" | "author_model_required_for_authoring" | "author_contract_planning_failed" | "author_contract_clarification_required" | "author_contract_review_failed" | "author_code_generation_failed" | "author_test_generation_failed" | "author_generated_code_failed" | "author_model_did_not_contribute" | "author_validation_not_contract_driven" | "author_non_llm_business_logic_detected" | "author_non_llm_artifact_maker_detected" | "author_required_artifact_overwritten" | "budget_exhausted_tokens" | "budget_exhausted_tool_calls" | "budget_exhausted_steps" | "budget_exhausted_wall_time" | "budget_exhausted_file_count" | "approval_declined" | "user_abandoned" | "sandbox_crash" | "workflow_interrupted" | "unknown";
        /**
         * EvalRunResult
         * @description Per-scenario run outcome.
         */
        EvalRunResult: {
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Diff Path */
            diff_path?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Passed */
            passed: boolean;
            /** Scenario Id */
            scenario_id: string;
        };
        /**
         * EvalRunSummary
         * @description Aggregate eval-run outcome.
         */
        EvalRunSummary: {
            /** Completed At */
            completed_at?: string | null;
            /** Failed */
            failed: number;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Passed */
            passed: number;
            /** Per Tag */
            per_tag?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Results */
            results?: components["schemas"]["EvalRunResult"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Total */
            total: number;
        };
        /**
         * EventKind
         * @description Closed enum of event kinds. Adding requires ADR.
         * @enum {string}
         */
        EventKind: "workflow_started" | "workspace_allocated" | "template_seeded" | "file_uploaded" | "schema_detected" | "decision_input" | "question_asked" | "answer_received" | "requirements_drafted" | "requirements_confirmed" | "phase_transitioned" | "model_called" | "tool_invoked" | "tool_observed" | "file_written" | "patch_applied" | "approval_requested" | "approval_granted" | "approval_declined" | "execution_started" | "execution_completed" | "execution_failed" | "test_run_started" | "test_run_completed" | "validation_run" | "artifact_generated" | "budget_warned" | "budget_exhausted" | "repair_problem_received" | "agent_summary_produced" | "reproduction_result" | "diagnosis_produced" | "patch_proposed" | "repair_report_generated" | "workflow_completed" | "workflow_failed" | "session_auto_archived";
        /**
         * FailureMitigation
         * @description Computed guidance for finance users when a session ends in failure.
         */
        FailureMitigation: {
            /**
             * Can Download Archive
             * @default false
             */
            can_download_archive: boolean;
            /**
             * Can Resume
             * @default false
             */
            can_resume: boolean;
            /** Evidence Items */
            evidence_items?: string[];
            /** Failure Category */
            failure_category: string;
            /** Mitigation Actions */
            mitigation_actions?: components["schemas"]["MitigationAction"][];
            primary_action: components["schemas"]["MitigationAction"];
            /**
             * Retry Safe
             * @default false
             */
            retry_safe: boolean;
            /** Secondary Actions */
            secondary_actions?: components["schemas"]["MitigationAction"][];
            /**
             * Technical Details Ref
             * @default events
             */
            technical_details_ref: string;
            /** User Summary */
            user_summary: string;
            /** User Title */
            user_title: string;
            /** What We Found */
            what_we_found?: string | null;
        };
        /**
         * FileUploadResponse
         * @description POST /sessions/{id}/files response.
         */
        FileUploadResponse: {
            /** Filename */
            filename: string;
            /** Hash Sha256 */
            hash_sha256: string;
            /** Relative Path */
            relative_path: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Uploaded File Id
             * Format: uuid
             */
            uploaded_file_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Provider */
            llm_provider?: string | null;
            /**
             * Service
             * @default agentforge-api
             */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /**
         * LoadFixtureResponse
         * @description POST /sessions/{id}/load_fixture/{name} response.
         *
         *     The repair wizard's InputStage uses this so a demo run does not
         *     require the user to package their own ZIP. Only the bundled
         *     fixtures under :attr:`Settings.fixtures_broken_agents_root` can be
         *     loaded; arbitrary paths are rejected at the boundary (INV-5 — the
         *     workspace path discipline applies symmetrically to writes from
         *     HTTP-side helpers).
         */
        LoadFixtureResponse: {
            /** Files Copied */
            files_copied: string[];
            /** Fixture Name */
            fixture_name: string;
            /**
             * Loaded At
             * Format: date-time
             */
            loaded_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Staged Golden Path */
            staged_golden_path?: string | null;
        };
        /**
         * MitigationAction
         * @description User-facing mitigation actions for failed sessions.
         * @enum {string}
         */
        MitigationAction: "start_new_session" | "edit_workflow_description" | "upload_replacement_file" | "answer_clarification" | "retry_same_inputs" | "download_audit_package" | "open_technical_details" | "open_repair" | "provide_expected_output" | "simplify_workflow" | "increase_budget" | "upload_problem_report";
        /**
         * ResumeManifest
         * @description Shape of ``manifest.json`` on disk for a session.
         */
        ResumeManifest: {
            budget: components["schemas"]["BudgetStatus"];
            completion?: components["schemas"]["CompletionMetadata"] | null;
            /** Current Phase */
            current_phase: string | null;
            /** Current Step */
            current_step: number;
            /** File Hashes */
            file_hashes?: {
                [key: string]: string;
            };
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            workflow: components["schemas"]["Workflow"];
            /** Workspace Path */
            workspace_path: string;
        };
        /**
         * Session
         * @description Full session row.
         */
        Session: {
            budget?: components["schemas"]["BudgetStatus"];
            /** Completed At */
            completed_at?: string | null;
            /** Current Phase */
            current_phase?: string | null;
            /**
             * Current Step
             * @default 0
             */
            current_step: number;
            failure_mitigation?: components["schemas"]["FailureMitigation"] | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Last Event Id */
            last_event_id?: string | null;
            /**
             * Manifest Schema Version
             * @default 1
             */
            manifest_schema_version: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** @default created */
            status: components["schemas"]["SessionStatus"];
            terminal_error_code?: components["schemas"]["ErrorCode"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            workflow: components["schemas"]["Workflow"];
            /** Workspace Path */
            workspace_path: string;
        };
        /**
         * SessionAnswerRequest
         * @description POST /sessions/{id}/answer body.
         *
         *     Used when the agent loop has emitted a ``question_asked`` event and
         *     is paused on ``paused_user``. The answer is recorded as an
         *     ``answer_received`` event so the next loop invocation can resume.
         */
        SessionAnswerRequest: {
            /** Answer */
            answer: string;
        };
        /**
         * SessionAnswerResponse
         * @description POST /sessions/{id}/answer response.
         */
        SessionAnswerResponse: {
            /**
             * Accepted At
             * Format: date-time
             */
            accepted_at: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * SessionArchiveResponse
         * @description POST /sessions/{id}/archive response.
         */
        SessionArchiveResponse: {
            /**
             * Archived At
             * Format: date-time
             */
            archived_at: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionBudgetBreakdownItem
         * @description Per-session token usage for the lifetime budget summary.
         */
        SessionBudgetBreakdownItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["SessionStatus"];
            /** Tokens Used */
            tokens_used: number;
            workflow: components["schemas"]["Workflow"];
        };
        /**
         * SessionBudgetSummary
         * @description Aggregate token usage across all non-deleted sessions.
         */
        SessionBudgetSummary: {
            /** Lifetime Tokens Used */
            lifetime_tokens_used: number;
            /** Recent Sessions */
            recent_sessions?: components["schemas"]["SessionBudgetBreakdownItem"][];
            /** Session Count */
            session_count: number;
        };
        /**
         * SessionCancelResponse
         * @description POST /sessions/{id}/cancel response.
         */
        SessionCancelResponse: {
            /**
             * Cancelled At
             * Format: date-time
             */
            cancelled_at: string;
            /** Event Id */
            event_id?: string | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
            /** Terminal Error Code */
            terminal_error_code?: string | null;
        };
        /**
         * SessionCreate
         * @description Request body: ``POST /sessions``.
         */
        SessionCreate: {
            workflow: components["schemas"]["Workflow"];
        };
        /**
         * SessionEventsResponse
         * @description GET /sessions/{id}/events response.
         */
        SessionEventsResponse: {
            /** Events */
            events: components["schemas"]["WorkspaceEvent"][];
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * SessionFinaliseRequest
         * @description POST /sessions/{id}/finalise body.
         */
        SessionFinaliseRequest: {
            /** Summary */
            summary?: string | null;
        };
        /**
         * SessionFinaliseResponse
         * @description POST /sessions/{id}/finalise response.
         *
         *     Mirrors the in-loop ``finalise_session`` tool semantics: refuses
         *     without a recorded ``ARTIFACT_GENERATED`` event, otherwise marks
         *     the session ``completed`` in both the manifest and the DB row.
         */
        SessionFinaliseResponse: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Finalised At
             * Format: date-time
             */
            finalised_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        };
        /** SessionList */
        SessionList: {
            /** Sessions */
            sessions: components["schemas"]["SessionListItem"][];
        };
        /**
         * SessionListItem
         * @description Compact session row for the dashboard list.
         */
        SessionListItem: {
            /** Current Phase */
            current_phase: string | null;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            workflow: components["schemas"]["Workflow"];
        };
        /**
         * SessionListView
         * @description Filter for ``GET /sessions`` dashboard tabs.
         * @enum {string}
         */
        SessionListView: "active" | "archived" | "deleted";
        /**
         * SessionRestoreResponse
         * @description POST /sessions/{id}/restore response.
         */
        SessionRestoreResponse: {
            /**
             * Restored At
             * Format: date-time
             */
            restored_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionRunRequest
         * @description POST /sessions/{id}/run body.
         *
         *     The orchestrator translates this into the first ``ModelMessage`` the
         *     agent loop sees. ``user_message`` is the workflow description (author
         *     flow) or the problem report (repair flow). ``template_hint`` is a
         *     soft signal — recorded as a ``DECISION_INPUT`` event so the model
         *     sees which template the user picked from the wizard.
         */
        SessionRunRequest: {
            /**
             * Template Hint
             * @description Optional template name (e.g. 'bank_categoriser') from the wizard's template picker. Recorded as a DECISION_INPUT event so the model knows which template to seed.
             */
            template_hint?: string | null;
            /**
             * User Message
             * @description Free-text description from the wizard's textarea. Author flow: the workflow description. Repair flow: the problem report. Wrapped in <user_message> delimiters before being passed to the model (INV-10).
             */
            user_message?: string | null;
        };
        /**
         * SessionRunResponse
         * @description POST /sessions/{id}/run response (202 Accepted).
         *
         *     The orchestrator runs on a background asyncio task; the client polls
         *     /events to follow progress and re-fetches /sessions/{id} once a
         *     terminal status appears.
         */
        SessionRunResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "created" | "running" | "paused_user" | "paused_approval" | "completed" | "failed_budget" | "failed_model" | "failed_sandbox" | "failed_user_reject" | "failed_other" | "auto_archived";
        /**
         * UploadAgentZipResponse
         * @description POST /sessions/{id}/upload_agent_zip response.
         *
         *     The repair wizard's InputStage offers ZIP upload as an alternative
         *     to the bundled-fixture picker — the user packages their own broken
         *     agent + problem report into a zip, the backend extracts it into
         *     ``${workspace}/working/`` (with zip-slip + size + file-count
         *     defences), and the repair flow runs against it the same way it
         *     runs against a bundled fixture.
         *
         *     INV-5: every extracted entry is resolved through
         *     :meth:`WorkspaceManager.resolve_in`; entries that would escape
         *     ``working/`` are rejected, the partial extraction is rolled back,
         *     and the call returns 400.
         */
        UploadAgentZipResponse: {
            /** Archive Filename */
            archive_filename: string;
            /** Files Extracted */
            files_extracted: string[];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Staged Golden Path */
            staged_golden_path?: string | null;
            /** Total Uncompressed Bytes */
            total_uncompressed_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationLayerSummary
         * @description One layer's outcome rolled into the manifest.
         */
        ValidationLayerSummary: {
            /** Layer */
            layer: string;
            /** Status */
            status: string;
        };
        /**
         * Workflow
         * @enum {string}
         */
        Workflow: "author" | "repair";
        /**
         * WorkspaceEvent
         * @description One line of ``events.jsonl``.
         *
         *     The ``payload`` is intentionally typed loosely here so the event log
         *     can serialise discriminated payloads without coupling this module to
         *     every payload class. Validation of the typed payload happens at the
         *     emission site (``event_log.append``) and on read.
         */
        WorkspaceEvent: {
            actor_type: components["schemas"]["ActorType"];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            kind: components["schemas"]["EventKind"];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Prev Event Id */
            prev_event_id?: string | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Step */
            step: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    export_audit_audit_export__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_eval_run_evals_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"];
                };
            };
        };
    };
    trigger_eval_run_evals_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Dashboard filter: active (default), archived, or recently deleted (last 30 days). */
                view?: components["schemas"]["SessionListView"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_summary_sessions_budget_summary_get: {
        parameters: {
            query?: {
                recent_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionBudgetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session UUID */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_endpoint_sessions__session_id__delete: {
        parameters: {
            query?: {
                /** @description When true, permanently removes the session and workspace. When false (default), moves the session to Recently deleted. */
                permanent?: boolean;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_sessions__session_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_sessions__session_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_session_endpoint_sessions__session_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionArchiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_archive_sessions__session_id__archive_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_sessions__session_id__artifacts__relative_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                relative_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_session_endpoint_sessions__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_events_sessions__session_id__events_get: {
        parameters: {
            query?: {
                /** @description Return only events strictly after this event id. Used by the frontend polling loop. */
                after?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_sessions__session_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_sessions__session_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalise_session_endpoint_sessions__session_id__finalise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionFinaliseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFinaliseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_fixture_sessions__session_id__load_fixture__fixture_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                fixture_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadFixtureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_sessions__session_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDeclineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_session_endpoint_sessions__session_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_session_sessions__session_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_agent_zip_sessions__session_id__upload_agent_zip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_agent_zip_sessions__session_id__upload_agent_zip_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAgentZipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
